// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe1B1mImSMv0ZTKWZvjgc0USki2ls8BNw',
    appId: '1:511457832412:web:98c7f0c27363ee36b3b319',
    messagingSenderId: '511457832412',
    projectId: 'phone-login-d4f42',
    authDomain: 'phone-login-d4f42.firebaseapp.com',
    storageBucket: 'phone-login-d4f42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPWvizzK8W9WZqFgllYQipJz1dP3KkL8',
    appId: '1:511457832412:android:3498c144774f2c94b3b319',
    messagingSenderId: '511457832412',
    projectId: 'phone-login-d4f42',
    storageBucket: 'phone-login-d4f42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ne4hYPtj14XUzqvAQVky7s1QuLiZhXw',
    appId: '1:511457832412:ios:f2f09ff236729944b3b319',
    messagingSenderId: '511457832412',
    projectId: 'phone-login-d4f42',
    storageBucket: 'phone-login-d4f42.appspot.com',
    iosClientId: '511457832412-ur2l9up3dgjedunttr8rhspje282kvmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneLogin',
  );
}
